package dc.longshot.models;

public enum SpriteKey {

	CROSSHAIRS, ROCK, STAR, CIRCLE, CLOUD, WHITE, GREEN, SHOOTER, SHOOTER_OUTLINE, CANNON, PELLET, BULLET, MISSILE, 
	NUKE, UFO, UFO_GLOW, SAW, BUG_HEAD, BUG_BODY
	
}
